import { createRequire } from 'node:module';
const require = createRequire(process.env.PLAYWRIGHT_MODULE_ROOT ? process.env.PLAYWRIGHT_MODULE_ROOT.replace(/[\\/]$/, '') + '/package.json' : import.meta.url);
const { chromium } = require('playwright');
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await page.goto('http://127.0.0.1:5173/');
await page.getByRole('heading', { name: 'Make yourself at ~home.' }).waitFor();
await page.getByRole('button', { name: 'B An operating system', exact: false }).count();
await page.locator('.answers button').filter({ hasText: 'An operating system' }).click();
await page.getByRole('button', { name: 'Next challenge' }).click();
await page.locator('.answers button').filter({ hasText: 'By typing short commands' }).click();
await page.getByRole('button', { name: 'Next challenge' }).click();
await page.locator('.answers button').filter({ hasText: 'Uppercase and lowercase' }).click();
await page.getByRole('button', { name: 'Next challenge' }).click();
await page.locator('.answers button').filter({ hasText: 'They use a Linux-based' }).click();
await page.getByRole('button', { name: 'Next challenge' }).click();
await page.locator('.answers button').filter({ hasText: 'demos are simulated and safe' }).click();
await page.getByRole('button', { name: 'See my results' }).click();
await page.getByRole('heading', { name: 'Command mastered!' }).waitFor();
await page.reload();
await page.locator('.hero-badge strong').filter({ hasText: '1' }).waitFor();
await page.getByRole('textbox', { name: 'Search all commands' }).fill('chmod');
await page.locator('.command-tabs button').filter({ hasText: /^chmod$/ }).click();
await page.locator('.lesson-heading h2').filter({ hasText: 'chmod' }).waitFor();
await page.reload();
await page.locator('.lesson-heading h2').filter({ hasText: 'chmod' }).waitFor();
await page.getByRole('button', { name: 'Light mode' }).click();
await page.reload();
await page.getByRole('button', { name: 'Dark mode' }).waitFor();
await page.getByRole('button', { name: 'Dark mode' }).click();
await page.screenshot({ path: 'preview-desktop.png', fullPage: true });
await page.setViewportSize({ width: 390, height: 844 });
await page.screenshot({ path: 'preview-mobile.png', fullPage: true });
const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth);
if (overflow) throw new Error('Mobile page overflows');
if (errors.length) throw new Error(errors.join('\n'));
console.log('Browser checks passed: 5-question mastery, saved progress, search, resume, theme, mobile overflow, no runtime errors.');
await browser.close();

